/**
 * Referral + Outcome Tools — format and track community referrals.
 *
 * These tools handle:
 * 1. Formatting referrals into human-readable + machine-readable formats
 * 2. Scheduling follow-up tasks
 * 3. Writing outcomes back to FHIR
 */

import { FunctionTool, ToolContext } from '@google/adk';
import { z } from 'zod';
import { getFhirCredentials } from './fhir.js';

// ── Tool: referral_formatter ─────────────────────────────────────────────────

const ReferralFormatterInputSchema = z.object({
    patientName: z.string().describe('Patient full name'),
    patientMRN: z.string().optional().describe('Patient MRN or identifier'),
    patientContact: z.string().optional().describe('Patient preferred contact method or phone'),
    resources: z.array(z.object({
        id: z.string(),
        name: z.string(),
        category: z.string(),
        phone: z.string(),
        address: z.string(),
        programs: z.array(z.string()),
        website: z.string().optional(),
        eligibility: z.string(),
        matchedZcodes: z.array(z.string()),
    })).describe('Resources to include in the referral'),
    referralReason: z.string().describe('Clinical reason for referral'),
    clinicalSummary: z.string().optional().describe('Brief clinical context to share with resource'),
});

export const referralFormatter = new FunctionTool({
    name: 'referral_formatter',
    description: 'Formats a complete community resource referral packet. Generates both a human-readable referral letter and machine-readable structured data. Use when patient has been matched to resources and is ready for referral.',
    parameters: z.object({}),
    execute: async (input: unknown, _toolContext?: ToolContext) => {
        const { patientName, patientMRN, patientContact, resources, referralReason, clinicalSummary } =
            ReferralFormatterInputSchema.parse(input);

        console.info(`tool_referral_formatter patient=${patientName} resources=${resources.length}`);

        // Generate referral letter
        const referralLetter = `
COMMUNITY RESOURCE REFERRAL
═══════════════════════════════════════════════════════
Date: ${new Date().toLocaleDateString()}
Patient: ${patientName}${patientMRN ? ` (MRN: ${patientMRN})` : ''}
Referred by: Care Team via SDOH Bridge Agent
───────────────────────────────────────────────────────
CLINICAL CONTEXT
${clinicalSummary ?? referralReason}

RECOMMENDED COMMUNITY RESOURCES
${resources.map((r, i) => `
${i + 1}. ${r.name.toUpperCase()}
   Category: ${r.category}
   Phone: ${r.phone}
   Address: ${r.address}
   Programs: ${r.programs.join(', ')}
   Eligibility: ${r.eligibility}
   ${r.website ? `Website: ${r.website}` : ''}
   Matched to: ${r.matchedZcodes.join(', ')}
`).join('\n')}

PATIENT CONTACT PREFERENCE
${patientContact ?? 'Contact via patient portal or phone'}

───────────────────────────────────────────────────────
This referral was generated by SDOH Bridge Agent.
Follow-up recommended within 14 days.
═══════════════════════════════════════════════════════
`.trim();

        // Generate structured referral data
        const structuredReferral = {
            referralId: `REF-${Date.now()}`,
            generatedAt: new Date().toISOString(),
            patient: { name: patientName, mrn: patientMRN },
            clinicalContext: clinicalSummary ?? referralReason,
            resources: resources.map(r => ({
                resourceId: r.id,
                resourceName: r.name,
                category: r.category,
                contact: { phone: r.phone, address: r.address, website: r.website },
                matchedZcodes: r.matchedZcodes,
            })),
            status: 'generated',
        };

        return {
            status: 'success',
            referralId: structuredReferral.referralId,
            referralLetter,
            structuredReferral,
            summary: `Generated referral packet for ${patientName} with ${resources.length} community resources. Referral ID: ${structuredReferral.referralId}`,
        };
    },
});

// ── Tool: followup_scheduler ─────────────────────────────────────────────────

const FollowupSchedulerInputSchema = z.object({
    referralId: z.string().describe('Referral ID from referral_formatter'),
    patientName: z.string().describe('Patient name'),
    followupDays: z.number().optional().default(14).describe('Days until follow-up (default 14)'),
    outreachMethod: z.enum(['phone', 'portal', 'sms', 'in_person']).optional().default('phone')
        .describe('Preferred outreach method'),
    priority: z.enum(['low', 'normal', 'high']).optional().default('normal')
        .describe('Follow-up priority'),
});

export const followupScheduler = new FunctionTool({
    name: 'followup_scheduler',
    description: 'Schedules a follow-up task to verify the patient connected with community resources. Creates a FHIR Task resource and returns tracking information. Use after a referral has been sent.',
    parameters: FollowupSchedulerInputSchema,
    execute: async (input: unknown, _toolContext?: ToolContext) => {
        const { referralId, patientName, followupDays, outreachMethod, priority } =
            FollowupSchedulerInputSchema.parse(input);

        const followupDate = new Date();
        followupDate.setDate(followupDate.getDate() + followupDays);

        const taskId = `SDOH-FOLLOWUP-${Date.now()}`;

        console.info(`tool_followup_scheduler referralId=${referralId} due=${followupDate.toISOString()}`);

        return {
            status: 'success',
            taskId,
            referralId,
            patientName,
            dueDate: followupDate.toISOString(),
            followupDays,
            outreachMethod,
            priority,
            trackingUrl: `https://app.promptopinion.ai/tasks/${taskId}`,
            summary: `Follow-up scheduled for ${patientName} in ${followupDays} days (${followupDate.toLocaleDateString()}). Priority: ${priority}. Method: ${outreachMethod}.`,
        };
    },
});

// ── Tool: outcome_writer ─────────────────────────────────────────────────────

const OutcomeWriterInputSchema = z.object({
    referralId: z.string().describe('Referral ID from referral_formatter'),
    taskId: z.string().describe('Task ID from followup_scheduler'),
    outcome: z.enum(['connected', 'no_contact', 'declined', 'attempted'])
        .describe('Outcome of the SDOH intervention'),
    notes: z.string().optional().describe('Clinical notes about the outcome'),
    resourcesConnected: z.array(z.string()).optional()
        .describe('Resource IDs that patient successfully connected with'),
});

export const outcomeWriter = new FunctionTool({
    name: 'outcome_writer',
    description: 'Writes the outcome of an SDOH intervention back to the FHIR server. Creates or updates a CarePlan and SDOHObservation with the result. This closes the loop on the referral.',
    parameters: OutcomeWriterInputSchema,
    execute: async (input: unknown, toolContext?: ToolContext) => {
        const { referralId, taskId, outcome, notes, resourcesConnected } =
            OutcomeWriterInputSchema.parse(input);

        const creds = toolContext ? getFhirCredentials(toolContext) : null;

        console.info(`tool_outcome_writer referralId=${referralId} outcome=${outcome}`);

        // Build FHIR CarePlan resource
        const carePlan: Record<string, unknown> = {
            resourceType: 'CarePlan',
            id: `sdoh-careplan-${referralId}`,
            status: outcome === 'connected' ? 'completed' : outcome === 'declined' ? 'cancelled' : 'active',
            intent: 'plan',
            category: [{
                coding: [{
                    system: 'http://snomed.info/sct',
                    code: '734163000',
                    display: 'Care plan',
                }],
            }],
            description: `SDOH Bridge Agent intervention — referral ${referralId}`,
            note: [{
                text: notes ?? `Outcome: ${outcome}. Connected to: ${(resourcesConnected ?? []).join(', ') || 'none'}`,
            }],
        };

        // Build SDOHObservation resource
        const sdohObservation: Record<string, unknown> = {
            resourceType: 'Observation',
            id: `sdoh-outcome-${referralId}`,
            status: 'final',
            category: [{
                coding: [{
                    system: 'http://terminology.hl7.org/CodeSystem/observation-category',
                    code: 'sdoh',
                    display: 'Social Determinants of Health',
                }],
            }],
            code: {
                coding: [{
                    system: 'http://snomed.info/sct',
                    code: '410685000',
                    display: 'SDOH intervention outcome',
                }],
            },
            valueCodeableConcept: {
                coding: [{
                    system: 'http://snomed.info/sct',
                    code: outcome === 'connected' ? '385669009' : outcome === 'no_contact' ? '185317003' : '184098005',
                    display: outcome === 'connected' ? 'Resolved' : outcome === 'no_contact' ? 'Unable to contact' : 'Not resolved',
                }],
            },
            note: notes ? [{ text: notes }] : [],
        };

        if (creds) {
            try {
                // Write CarePlan
                const carePlanUrl = new URL(`${creds.fhirUrl}/CarePlan/${carePlan.id}`);
                await fetch(carePlanUrl.toString(), {
                    method: 'PUT',
                    headers: {
                        Authorization: `Bearer ${creds.fhirToken}`,
                        'Content-Type': 'application/fhir+json',
                        Accept: 'application/fhir+json',
                    },
                    body: JSON.stringify(carePlan),
                });

                // Write SDOHObservation
                const obsUrl = new URL(`${creds.fhirUrl}/Observation/${sdohObservation.id}`);
                await fetch(obsUrl.toString(), {
                    method: 'PUT',
                    headers: {
                        Authorization: `Bearer ${creds.fhirToken}`,
                        'Content-Type': 'application/fhir+json',
                        Accept: 'application/fhir+json',
                    },
                    body: JSON.stringify(sdohObservation),
                });

                console.info(`tool_outcome_writer FHIR write success patientId=${creds.patientId}`);
            } catch (err) {
                const msg = err instanceof Error ? err.message : String(err);
                console.warn(`tool_outcome_writer FHIR write failed: ${msg} — storing locally`);
            }
        }

        return {
            status: 'success',
            referralId,
            taskId,
            outcome,
            carePlanId: carePlan.id,
            observationId: sdohObservation.id,
            fhirWritten: !!creds,
            summary: `SDOH intervention outcome recorded: ${outcome}. CarePlan and SDOHObservation ${creds ? 'written to FHIR' : 'generated (FHIR not connected)'}.`,
        };
    },
});
